### ISSUE TITLE
AutoBitLocker resource does not encrypt volumes with drive letter assigned

### ISSUE THREAD

**Issue by MartinVokurek** [PowerShell/xBitlocker#10]
Function GetAutoBitLockerStatus in MSFT_xBLAutoBitlocker.psm1 uses `$allBlvs = Get-BitLockerVolume | where {$_.VolumeType -eq "Data"}` at line 365 to get list of Data volumes and
`Get-Volume -Path $blv.MountPoint` to filter Fixed vs Removable at line 381. This works fine for volumes without drive letter assigned (mountpoint returned by `Get-BitlockerVolume` is `\\?\Volume{<guid>}\`

But for volumes with drive letter assigned, `Get-Volume -Path` does not work. In that case, it is necessary to use `Get-Volume -DriveLetter` instead.

**Comment by johlju** [comment]
Labeling this as an enhancement and help wanted so anyone in the community can run with it.

Maybe we can use Split-Path to determine which named parameter to use?

```powershell
PS > Split-Path -Path '\\?\Volume{<guid>}\' -IsAbsolute
False
PS > Split-Path -Path 'E:\' -IsAbsolute
True
```
