### ISSUE TITLE
AutoBitLocker resource incorrectly identifies Fixed vs Removable drives

### ISSUE THREAD

**Issue by MartinVokurek** [PowerShell/xBitlocker#11]
Current implementation of AutoBitLocker resource uses `Get-Volume` to differentiate between Fixed and Removable drives. This does not work correctly as there are drives reported as Fixed, yet Bitlocker evaluates them as Removable and therefore applies different GPO settings to them. I saw this for certain HP SAS controllers, VMware can also behave this way (https://kb.vmware.com/s/article/1012225) - seems to be related to the way storage controller reports disk capabilities to the OS.

Instead of using `Get-Volume`, I found `\root\cimv2\security\microsoftvolumeencryption:Win32_EncryptableVolume.VolumeType` property to correctly report volume types as evaluated by Bitlocker:
0 - OS volume
1 - Fixed volume
2 - Removable volume

**Comment by johlju** [comment]
Do you have example output where Get-Volume report the wrong type, but CIM reports it correctly? Labeling this as a bug and help wanted.

**Comment by MartinVokurek** [comment]
Sure, I found that even my SSD drive connected via USB dongle behaves this way:
```
gwmi -Namespace root\cimv2\security\microsoftvolumeencryption win32_encryptablevolume -filter "DriveLetter='F:'"|select driveletter,volumetype|fl

driveletter : F:
volumetype  : 2
```

```
get-volume -driveletter "F"|select driveletter,drivetype|fl

driveletter : F
DriveType   : Fixed
```

**Comment by johlju** [comment]
I see that you referenced this issue in commits. You are welcome to send in a PR resolving this! 🙂

**Comment by MartinVokurek** [comment]
Will do once I have time to test the fix, possibly over the weekend.
