### ISSUE TITLE
UsedSpaceOnly, SkipHardwareTest, HardwareEncryption properties cannot be set to False

### ISSUE THREAD

**Issue by MartinVokurek** [PowerShell/xBitlocker#12]
When defining xBLBitlocker or xBLAutoBitlocker resources, UsedSpace, SkipHardwareTest or HardwareEncryption Boolean properties can be defined, but no matter if they are defined as $True or $False, they are always processed as $True during Enable-Bitlocker.
That is because the properties are tested for existence on lines 133-156 of BitlockerCommon.ps1. And if they exist, they are hardcoded to $true in $params hashtable

I'm not sure what was the original idea here, because I can see that Enable-Bitlocker defines these parameters as switches, therefore if present, they are assumed true. And the README says the parameters behave "the same as in Enable-Bitlocker"

However, for me personally, this is incorrect behavior of DSC resource, because the resource happily accepts e.g. UsedSpaceOnly=$false, yet it silently passes UsedSpaceOnly=$true to Enable-Bitlocker, creating possible significant security issue.

**Comment by johlju** [comment]
Sounds like a bug that has sneaked passed because there are no unit tests in this resource module.
