### ISSUE TITLE
[xBLBitlocker ] Get-WindowsFeature not found if Carbon is installed

### ISSUE THREAD

**Issue by bozho** [PowerShell/xBitlocker#25]
#### Details of the scenario you tried and the problem that is occurring
`Test-TargetResource` calls `CheckForPreReqs`, which in turn executes `Get-WindowsFeature`. 

Powershell module Carbon also provides a `Get-WindowsFeature` cmdlet, and if it's installed, the `Get-WindowsFeature` call fails if `ServerManager` module has not been explicitly imported, or the call is changed to `ServerManager\Get-WindowsFeature`

#### Suggested solution to the issue
Change `CheckForPreReqs` to either import `ServerManager` or change the calls to `ServerManager\Get-WindowsFeature`.

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2485.amd64fre.rs1_release.180827-1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.2485                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.2485                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.2.0.0

**Comment by bozho** [comment]
I'm happy to provide a patch for a chosen solution.

**Comment by johlju** [comment]
Import the module is one solution, another solution is that the clobber problem that Carbon module introducing is resolved instead. 🙂 
I'm not seeing a problem adding a `Import-Module` call to the helper function, it doesn't hurt. Only minor potential problem is if the module name is different depending on Windows version in the future.

**Comment by mhendric** [comment]
I personally don't see this as a problem with xBitlocker. Like @johlju alluded to, I think this is more a problem with Carbon in that they created a custom function with the same name as a built-in Windows PowerShell function. I think this should be fixed at the root of the problem (Carbon), not downstream (xBitlocker). @bozho , let me know if you disagree, or if you still think this should be fixed in xBitlocker (and why). Thanks.

**Comment by mhendric** [comment]
Closing this Issue, as I see this as an issue with Carbon, not xBitlocker. If anyone disagrees, feel free to re-open and make your case.
